### ISSUE TITLE
Uncaught ReferenceError: child is not defined

### ISSUE THREAD

**Issue by mashvamps** [lsegal/atom-runner#108]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.3.2
**System**: Mac OS X 10.11.2
**Thrown From**: [atom-runner](https://github.com/lsegal/atom-runner) package, v2.5.1

### Stack Trace

Uncaught ReferenceError: child is not defined

```
At /Users/KiyoshiTakehara/.atom/packages/atom-runner/lib/atom-runner.coffee:116

ReferenceError: child is not defined
    at AtomRunner.stop (/Users/KiyoshiTakehara/.atom/packages/atom-runner/lib/atom-runner.coffee:116:32)
    at AtomRunner.stopAndClose (/Users/KiyoshiTakehara/.atom/packages/atom-runner/lib/atom-runner.coffee:124:6)
    at atom-workspace.<anonymous> (/Users/KiyoshiTakehara/.atom/packages/atom-runner/lib/atom-runner.coffee:72:58)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -5:27.7.0 run:file (atom-text-editor.editor.is-focused)
     -5:20.3.0 run:stop (div.atom-runner)
  3x -5:14 core:backspace (div.atom-runner)
     -5:11.5.0 core:confirm (div.atom-runner)
     -5:10.6.0 run:close (div.atom-runner)
     -4:51.8.0 tree-view:remove (li.file.entry.list-item.selected)
     -4:22.9.0 core:copy (atom-text-editor.editor.is-focused)
     -4:19.6.0 core:paste (atom-text-editor.editor.is-focused)
     -4:10.4.0 core:save (atom-text-editor.editor.is-focused)
     -3:23.7.0 run:file (atom-text-editor.editor.is-focused)
     -3:18.3.0 run:stop (div.atom-runner)
     -3:03.7.0 run:copy (div.atom-runner)
     -2:59.2.0 run:close (div.atom-runner)
     -0:24.1.0 run:file (atom-text-editor.editor.is-focused)
     -0:12.1.0 run:stop (div.atom-runner)
     -0:00.8.0 run:close (div.atom-runner)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ],
    "openEmptyEditorOnStart": false
  }
}
```

### Installed Packages

```coffee
# User
atom-runner, v2.5.1
autocomplete-python, v1.2.4
color-picker, v2.0.14
file-icons, v1.6.13
japanese-menu, v1.6.2
language-swift, v0.4.0
minimap, v4.19.0
monokai, v0.18.0

# Dev
No dev packages
```

**Comment by lsegal** [comment]
Fixed in v2.5.2
