### ISSUE TITLE
Uncaught TypeError: cmd.split is not a function

### ISSUE THREAD

**Issue by ColinOsborn** [lsegal/atom-runner#118]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.4.3
**System**: Mac OS X 10.11.3
**Thrown From**: [atom-runner](https://github.com/lsegal/atom-runner) package, v2.5.2

### Stack Trace

Uncaught TypeError: cmd.split is not a function

```
At /Users/colinosborn/.atom/packages/atom-runner/lib/atom-runner.coffee:134

TypeError: cmd.split is not a function
    at AtomRunner.execute (/Users/colinosborn/.atom/packages/atom-runner/lib/atom-runner.coffee:134:20)
    at AtomRunner.run (/Users/colinosborn/.atom/packages/atom-runner/lib/atom-runner.coffee:108:6)
    at atom-workspace.<anonymous> (/Users/colinosborn/.atom/packages/atom-runner/lib/atom-runner.coffee:69:57)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/colinosborn/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Users/colinosborn/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Users/colinosborn/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Users/colinosborn/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Users/colinosborn/Downloads/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Users/colinosborn/Downloads/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:04.0 core:save (atom-text-editor.editor.is-focused)
     -0:00.9.0 run:file (atom-text-editor.editor.is-focused)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
atom-runner, v2.5.2

# Dev
No dev packages
```

**Comment by lsegal** [comment]
Please provide an error report with proper reproduction steps, thank you!
