### ISSUE TITLE
Ubuntu14.04,Unable to find command: python3

### ISSUE THREAD

**Issue by RyanWWW** [lsegal/atom-runner#138]
When I try to run a simple python3 code, I get this error code:

`Unable to find command: python3
Are you sure PATH is configured correctly?
ENV PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
Error: spawn python3 ENOENT
    at exports._errnoException (util.js:837:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)`

my config is 

`"*":
  autosave:
    enabled: true
  core: {}
  editor:
    invisibles: {}
    showIndentGuide: true
    tabLength: 4
  "exception-reporting":
    userId: "1f13bd42-66e8-dbc1-4f3d-f6abd5460bf0"
  welcome:
    showOnStartup: false
  'runner':
    'scopes':
      'python':'python3'`

even if I change python3 to python, the problem still can't be solved 

And in my terminal

`ryan@ryanUbuntu:~$ which python3
/usr/bin/python3
`

It's strange because in my virtualBox, with the same setting there's no problem at all. But when I install Ubuntu14.04 formly, I get this problem.
I have reinstall my OS, can't help.

**Comment by RyanWWW** [comment]
solved by following
[http://mfctips.com/2016/03/07/atom-runner-unable-to-find-command-python-error-spawn-python-enoent/](url)
must open folder first otherwise you can't use atom-runner get error code  "can't find command"??? 
Are you serious?.?It's a bug?
