### ISSUE TITLE
Endless error message popups - Uncaught TypeError: view.appendFooter is not a function

### ISSUE THREAD

**Issue by RenaKunisaki** [lsegal/atom-runner#161]
[Enter steps to reproduce below:]

1. Enable package
2. Bind a key to `run:file`
3. Open a Python script and press the key
4. This error pops up about once per second until Atom is closed

**Atom Version**: 1.10.2
**Electron Version**: 1.4.1
**System**: linux 4.7.5-1-ARCH
**Thrown From**: [atom-runner](https://github.com/lsegal/atom-runner) package, v2.7.1

### Stack Trace

Uncaught TypeError: view.appendFooter is not a function

```
At /home/rena/.atom/packages/atom-runner/lib/atom-runner.coffee:183

TypeError: view.appendFooter is not a function
    at ChildProcess.<anonymous> (/home/rena/.atom/packages/atom-runner/lib/atom-runner.coffee:183:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
```

### Commands

```
     -1:34.7.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:34.5.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -1:34.4.0 core:cancel (atom-text-editor.editor.is-focused)
     -1:00.2.0 core:move-up (atom-text-editor.editor.is-focused)
     -1:00.2.0 core:move-right (atom-text-editor.editor.is-focused)
     -1:00.2.0 core:move-left (atom-text-editor.editor.is-focused)
     -1:00.2.0 core:move-down (atom-text-editor.editor.is-focused)
     -1:00.1.0 core:move-up (atom-text-editor.editor.is-focused)
     -1:00.1.0 core:move-down (atom-text-editor.editor.is-focused)
     -1:00.1.0 core:move-right (atom-text-editor.editor.is-focused)
     -1:00.1.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:57.5.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:46.3.0 core:cancel (linter-panel.)
     -0:22.9.0 editor:select-to-first-character-of-line (atom-text-editor.editor.mini.is-focused)
  2x -0:21.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.6.0 run:file (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "destroyEmptyPanes": false,
    "disabledPackages": [
      "rename-tabs"
    ],
    "projectHome": "/home/rena/projects"
  },
  "atom-runner": {
    "showOutputWindow": false
  }
}
```

### Installed Packages

```coffee
# User
atom-runner, v2.7.1 (active)
autocomplete-python, v1.8.6 (active)
copy-filename, v1.0.1 (active)
git-plus, v5.18.0 (active)
git-time-machine, v1.5.3 (inactive)
linter, v1.11.18 (active)
linter-python, v3.0.5 (active)
python-tools, v0.6.8 (active)
rename-tabs, v0.2.0 (inactive)
smart-tab-name, v1.0.5 (active)
tab-title, v0.3.3 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (active)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
find-and-replace, v0.201.0 (inactive)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by Kutsan** [comment]
Same and it's not funny.

**Comment by dragosmihaimt** [comment]
Same thing here, on the first day of download.
Has anyone found a fix ? :)
