### ISSUE TITLE
work not well on win-os when including "#!/usr/bin/env python"

### ISSUE THREAD

**Issue by dhqdqk** [lsegal/atom-runner#175]
# problem
when the python file including the codes "#!/usr/bin/env python", the atom-runner work wrong.
```
Unable to find command: /usr/bin/env
Are you sure PATH is configured correctly?

ENV PATH: E:\Program Files\python27;E:\Program Files\python27\Scripts;D:\Program Files\Java\bin;C:\Windows\system32;C:\Windows;C:\Windows\system32\wbem;C:\windows\system32\;E:\Program Files\Git\cmd;E:\DHQ\go\bin;C:\Users\Administrator\AppData\Local\Programs\Python\Python35\Scripts\;C:\Users\Administrator\AppData\Local\Programs\Python\Python35\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Users\Administrator\AppData\Local\atom\bin；C:\Users\Administrator\AppData\Local\Programs\Python\Python35\;C:\Users\Administrator\AppData\Local\atom\bin

Error: spawn /usr/bin/env ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```
The ENV PATH has been setted corecctly.
After deleting codes "#!/usr/bin/env python", it works well .
I think atom-runner cann't  ignore the shebang codes on win-os.

**Comment by lsegal** [comment]
Shebangs are explicitly handled on windows. This is a feature. An option to turn this off would be accepted but only as a pull request.
