### ISSUE TITLE
cannot run javascript

### ISSUE THREAD

**Issue by arno2233** [lsegal/atom-runner#221]
I am trying to learn javascript and wanted an editor. I typed some lines of code and have atom runner installed. this is what I get:

Atom Runner: test
Unable to find command: node Are you sure PATH is configured correctly?
ENV PATH: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Frameworks/Mono.framework/Versions/Current/Commands
Error: spawn node ENOENT at exports._errnoException (util.js:1050:11) at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32) at onErrorNT (internal/child_process.js:367:16) at _combinedTickCallback (internal/process/next_tick.js:80:11) at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by arno2233** [comment]
ok. I found it. I had to install node.js first.

How could I know that? I am just beginning to learn!
