### ISSUE TITLE
Error: spawn node ENOENT

### ISSUE THREAD

**Issue by ryanseys** [lsegal/atom-runner#37]
It was working for me and now after restarting Atom it no longer works. I am trying to run a `.js` file with Ctrl+R and just get this error:

```
Error: spawn node ENOENT
  at exports._errnoException (util.js:753:11)
  at Process.ChildProcess._handle.onexit (child_process.js:1051:32)
  at child_process.js:1142:20
  at process._tickCallback (node.js:364:11)
```

Any help with this issue would be great!

**Comment by ryanseys** [comment]
Nevermind I think Atom is just fucking up my PATH for some reason and has nothing to do with this module.
