### ISSUE TITLE
Failed to load the atom-runner package

### ISSUE THREAD

**Issue by klynton** [lsegal/atom-runner#48]
[Enter steps to reproduce below:]

1. Updated to version 0.190.0.
2. Re-opened Atom.

**Atom Version**: 0.190.0
**System**: Mac OS X 10.10.3
**Thrown From**: [atom-runner](https://github.com/lsegal/atom-runner) package, v2.3.0

### Stack Trace

Failed to load the atom-runner package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (/Users/klynton/Dropbox/Apps/Atom/packages/atom-runner/lib/atom-runner-view.coffee:4:199)
    at /Users/klynton/Dropbox/Apps/Atom/packages/atom-runner/lib/atom-runner-view.coffee:11:5
    at Object.<anonymous> (/Users/klynton/Dropbox/Apps/Atom/packages/atom-runner/lib/atom-runner-view.coffee:92:5)
    at Object.<anonymous> (/Users/klynton/Dropbox/Apps/Atom/packages/atom-runner/lib/atom-runner-view.coffee:94:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      "*.un~"
    ],
    "disabledPackages": [
      "autocomplete",
      "remember-session",
      "pain-split",
      "vim-mode",
      "atom-lint"
    ],
    "themes": [
      "one-dark-ui",
      "atom-light-syntax"
    ],
    "projectHome": "/Users/klynton/src",
    "audioBeep": false
  }
}
```

### Installed Packages

```coffee
# User
atom-django, v0.2.1
atom-erb, v0.1.0
atom-runner, v2.3.0
autocomplete-clang, v0.6.4
autocomplete-plus, v2.9.0
autoflow-diffable, v0.3.1
color-picker, v1.6.0
command-logger, v0.22.0
django-templates, v0.4.0
editor-stats, v0.17.0
git-plus, v4.4.11
go-plus, v3.3.6
language-puppet, v0.11.0
linter, v0.12.0
linter-clang, v2.25.1
linter-csslint, v0.0.11
linter-erb, v0.1.0
linter-flake8, v1.3.0
linter-flow, v0.1.4
linter-js-yaml, v1.0.0
linter-jsxhint, v0.1.1
linter-pep8, v0.1.0
linter-php, v0.0.12
linter-puppet-lint, v0.2.8
linter-pyflakes, v0.0.4
linter-shellcheck, v0.0.7
linter-tidy, v1.0.0
react, v0.11.2
tabs-to-spaces, v0.9.2

# Dev
No dev packages
```

**Comment by klynton** [comment]
Closed and re-opened Atom and it loaded fine this time.

**Comment by Listbd** [comment]
I get this error only if I run `atom --one`
