### ISSUE TITLE
Failed to load the atom-runner package

### ISSUE THREAD

**Issue by nanorepublica** [lsegal/atom-runner#52]
[Enter steps to reproduce below:]

1.  Start Atom - happens everytime

**Atom Version**: 0.194.0 :warning: **in 1.0 API Preview Mode** :warning:
**System**: Mac OS X 10.10.3
**Thrown From**: [atom-runner](https://github.com/lsegal/atom-runner) package, v2.3.0

### Stack Trace

Failed to load the atom-runner package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (/Users/amiller/.atom/packages/atom-runner/lib/atom-runner-view.coffee:4:199)
    at /Users/amiller/.atom/packages/atom-runner/lib/atom-runner-view.coffee:11:5
    at Object.<anonymous> (/Users/amiller/.atom/packages/atom-runner/lib/atom-runner-view.coffee:92:5)
    at Object.<anonymous> (/Users/amiller/.atom/packages/atom-runner/lib/atom-runner-view.coffee:94:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "excludeVcsIgnoredPaths": false,
    "disabledPackages": [
      "travis-ci-status"
    ],
    "themes": [
      "atom-dark-ui",
      "monokai"
    ],
    "projectHome": "/Users/amiller"
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.2.0
angularjs-helper, v0.8.0
angularjs-snippets, v0.10.2
atom-angularjs, v0.1.2
atom-cli-diff, v0.11.0
atom-django, v0.2.1
atom-jinja2, v0.5.0
atom-runner, v2.3.0
autocomplete-paths, v1.0.2
autocomplete-plus, v2.12.0
build, v0.29.0
color-picker, v1.7.0
command-logger, v0.23.0
django-templates, v0.4.0
editor-stats, v0.17.0
eval, v0.2.0
git-blame, v0.4.0
git-go, v1.0.1
git-grep, v0.9.0
git-history, v2.5.0
git-log, v0.3.0
git-tab-status, v1.7.0
inline-autocomplete, v1.0.4
jsonlint, v1.1.0
language-django, v0.1.1
language-docker, v1.1.3
language-puppet, v0.11.0
language-python-django-templates, v0.1.0
linter, v0.12.0
linter-puppet, v0.1.0
linter-puppet-lint, v0.2.8
minimap, v4.7.6
minimap-color-highlight, v4.1.0
minimap-find-and-replace, v4.2.0
minimap-git-diff, v4.1.2
minimap-highlight-selected, v4.2.1
minimap-selection, v4.2.0
monokai, v0.14.0
pretty-json, v0.3.3
project-colorize, v0.1.0
project-manager, v1.15.5
project-ring, v0.19.6
recent-files, v0.3.0
recent-projects, v0.3.0
script, v2.19.0
set-syntax, v0.2.1
update-packages, v0.1.0

# Dev
No dev packages
```

**Comment by lsegal** [comment]
Closing. Open a pull request to fix this, thanks!
