### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by wolli2710** [lsegal/atom-runner#67]
1. selected code to run
2. used crtl + shift + r
3. uncaught TypeError

the selected code was a simple ruby code: puts 'something'
ctrl + r executes the code very well...

**Atom Version**: 0.210.0
**System**: Mac OS X 10.10.3
**Thrown From**: [atom-runner](https://github.com/lsegal/atom-runner) package, v2.4.1

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Users/wolfgangvogl/.atom/packages/atom-runner/lib/atom-runner.coffee:142

TypeError: undefined is not a function
  at AtomRunner.execute (/Users/wolfgangvogl/.atom/packages/atom-runner/lib/atom-runner.coffee:142:33)
  at AtomRunner.run (/Users/wolfgangvogl/.atom/packages/atom-runner/lib/atom-runner.coffee:86:6)
  at atom-workspace.<anonymous> (/Users/wolfgangvogl/.atom/packages/atom-runner/lib/atom-runner.coffee:62:62)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:180:20)

```

### Commands

```
     -1:14.8.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:09.5.0 core:move-right (atom-text-editor.editor.is-focused)
     -1:06.6.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -1:03.0 symbols-view:toggle-project-symbols (atom-text-editor.editor.is-focused)
     -1:00.9.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -1:00.9.0 core:cancel (atom-text-editor.editor.mini.is-focused)
  2x -0:58.7.0 run:selection (atom-text-editor.editor.is-focused)
  3x -0:18.3.0 run:file (atom-text-editor.editor.is-focused)
     -0:00.6.0 run:selection (atom-text-editor.editor.is-focused)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.5
atom-runner, v2.4.1
minimap, v4.10.0

# Dev
No dev packages
```

**Comment by relisher** [comment]
I am also having this problem, code is simple javascript

**Comment by itbaby** [comment]
yea, I also have the issue.

**Comment by itbaby** [comment]
in fact , some of the issues opened by new chrome version. you can debug it with ctrl+alt+i then many of them can be fixed  by your self.

**Comment by robjloranger** [comment]
any update on this issue?

**Comment by lsegal** [comment]
Can't reproduce this in latest version, it may have been inadvertently fixed.
