### ISSUE TITLE
Uncaught Error: kill EINVAL

### ISSUE THREAD

**Issue by vrajakishore** [lsegal/atom-runner#87]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Microsoft Windows 10 Home Single Language
**Thrown From**: [atom-runner](https://github.com/lsegal/atom-runner) package, v2.4.4

### Stack Trace

Uncaught Error: kill EINVAL

```
At internal/child_process.js:374

Error: kill EINVAL
  at exports._errnoException (util.js:814:11)
  at ChildProcess.kill (internal/child_process.js:374:13)
  at AtomRunner.stop (C:\Users\m.v\.atom\packages\atom-runner\lib\atom-runner.coffee:117:14)
  at AtomRunner.execute (C:\Users\m.v\.atom\packages\atom-runner\lib\atom-runner.coffee:128:6)
  at AtomRunner.run (C:\Users\m.v\.atom\packages\atom-runner\lib\atom-runner.coffee:108:6)
  at atom-workspace.<anonymous> (C:\Users\m.v\.atom\packages\atom-runner\lib\atom-runner.coffee:69:57)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\m.v\AppData\Local\atom\app-1.0.19\resources\app.asar\src\command-registry.js:245:29)
  at C:\Users\m.v\AppData\Local\atom\app-1.0.19\resources\app.asar\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\m.v\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\m.v\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\m.v\AppData\Local\atom\app-1.0.19\resources\app.asar\src\window-event-handler.js:184:20)

```

### Commands

```
     -6:32.4.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
 12x -6:30.2.0 core:move-left (atom-text-editor.editor.is-focused)
  8x -6:27.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -6:25.8.0 core:move-up (atom-text-editor.editor.is-focused)
     -6:25.5.0 core:move-left (atom-text-editor.editor.is-focused)
     -6:23.2.0 core:move-down (atom-text-editor.editor.is-focused)
 10x -6:23 core:move-right (atom-text-editor.editor.is-focused)
     -6:14.2.0 core:save (atom-text-editor.editor.is-focused)
  4x -6:13.6.0 run:file (atom-text-editor.editor.is-focused)
undefined -4:26 core:move-down (div.settings-view.pane-item)
     -0:31.2.0 command-palette:toggle (div.atom-runner)
     -0:23.8.0 make-runner:run (div.atom-runner)
     -0:16.1.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:13.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:13.3.0 application:open-your-config (atom-text-editor.editor)
     -0:04.2.0 run:file (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.14
atom-runner, v2.4.4
auto-indent, v0.5.0
autocomplete-plus-python-jedi, v0.3.6
autocomplete-python, v0.6.0
django-test-runner, v0.3.0
language-javascript-subtlegradient, v0.1.0
make-runner, v1.1.12
python-autopep8, v0.1.3
script-runner, v1.8.4

# Dev
No dev packages
```

**Comment by lsegal** [comment]
I'm going to have to close this unless you can provide steps to reproduce this issue. Thanks.

**Comment by lsegal** [comment]
Feel free to reopen if you can provide reproduction steps.
