### ISSUE TITLE
Uncaught TypeError: editor.getSelection is not a function

### ISSUE THREAD

**Issue by shemerey** [lsegal/atom-runner#88]
steps to reproduce

1. open a [coffescript-koans](https://github.com/sleepyfox/coffeescript-koans)
2. hit `ctrl-R`

**Atom Version**: 1.0.19
**System**: Mac OS X 10.10.5
**Thrown From**: [atom-runner](https://github.com/lsegal/atom-runner) package, v2.4.4

### Stack Trace

Uncaught TypeError: editor.getSelection is not a function

```
At /Users/zork/.atom/packages/atom-runner/lib/atom-runner.coffee:168

TypeError: editor.getSelection is not a function
  at AtomRunner.execute (/Users/zork/.atom/packages/atom-runner/lib/atom-runner.coffee:168:33)
  at AtomRunner.run (/Users/zork/.atom/packages/atom-runner/lib/atom-runner.coffee:108:6)
  at atom-workspace.<anonymous> (/Users/zork/.atom/packages/atom-runner/lib/atom-runner.coffee:70:62)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:184:20)

```

### Commands

```
  2x -0:09.4.0 tree-view:toggle (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:07.5.0 tree-view:expand-directory (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:05.0 tree-view:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:03.0 run:selection (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "tool-bar-main",
      "imdone-atom",
      "ruby-block-converter"
    ],
    "themes": [
      "atom-dark-ui",
      "base16-tomorrow-dark-theme"
    ],
    "packagesWithKeymapsDisabled": [
      "git-plus",
      "last-cursor-position",
      "git-blame",
      "highlight-line",
      "merge-conflicts",
      "ruby-test-switcher"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-runner, v2.4.4
atom-spotify2, v2.1.2
atomdo, v0.6.0
autoclose-html, v0.19.0
esc2, v0.0.0
fuzzy-finder, v0.89.0
git-log, v0.4.1
highlight-line, v0.11.0
last-cursor-position, v0.9.0
linter, v1.7.2
linter-csslint, v1.0.7
linter-erb, v0.1.1
linter-js-standard, v3.2.0
linter-jshint, v1.2.1
linter-ruby, v1.1.1
pigments, v0.15.0
project-manager, v2.6.1
react, v0.12.10
regex-railroad-diagram, v0.10.3
rest-client, v0.4.0
tool-bar, v0.1.9
vim-mode, v0.60.0
vim-mode-visual-block, v0.2.13
vim-surround, v0.8.0

# Dev
esc2, v0.0.0
fuzzy-finder, v0.89.0
highlight-line, v0.11.0
```

**Comment by lsegal** [comment]
I'm going to have to close this unless you can provide steps to reproduce this issue. Thanks.

**Comment by shemerey** [comment]
steps to reproduce

open a coffescript-koans
hit ctrl-R

it was too fast, i hit save button by mistake

**Comment by lsegal** [comment]
Do you have no text editor active when you hit ctrl+R? As in, have you just started Atom and not highlighted any windows? Can you walk through the process more granularly, what you did when you started atom, etc.

**Comment by shairontoledo** [comment]
Same issue in my end, repro with:

1. Install `atom-runner` package
2. open a new file, fill it with a single `echo foo` line, save it as `test.sh`
3. select the line `echo foo`, shift+command+p then select "Run: Selection" ... crash!

```

**Atom Version**: 1.0.19
**System**: Mac OS X 10.10.5
**Thrown From**: [atom-runner](https://github.com/lsegal/atom-runner) package, v2.4.6


### Stack Trace

Uncaught TypeError: editor.getSelection is not a function

```
At /Users/shairon/.atom/packages/atom-runner/lib/atom-runner.coffee:168

TypeError: editor.getSelection is not a function
  at AtomRunner.execute (/Users/shairon/.atom/packages/atom-runner/lib/atom-runner.coffee:168:33)
  at AtomRunner.run (/Users/shairon/.atom/packages/atom-runner/lib/atom-runner.coffee:108:6)
  at atom-workspace.<anonymous> (/Users/shairon/.atom/packages/atom-runner/lib/atom-runner.coffee:70:62)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:184:20)

```

### Commands

```
     -7:23.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -7:22.4.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -7:22.4.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -7:18.9.0 editor:newline (atom-text-editor.editor.is-focused)
     -7:18.3.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -6:53.5.0 core:copy (div.package-readme.native-key-bindings)
     -6:50.3.0 core:paste (atom-text-editor.editor.is-focused)
  4x -5:26.6.0 core:undo (atom-text-editor.editor.is-focused)
     -2:55.7.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  3x -2:53 core:move-down (atom-text-editor.editor.mini.is-focused)
     -2:52.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:52.3.0 run:selection (atom-text-editor.editor)
     -0:05.7.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  3x -0:02.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:01.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:01.4.0 run:selection (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "atom-dark-syntax"
    ],
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-runner, v2.4.6
auto-run, v0.2.1
copy-path, v0.1.1
env-from-shell, v0.1.2
language-chef, v0.7.0
language-rspec-plus, v0.1.1
linter, v1.7.0
linter-rubocop, v0.2.7
linter-ruby, v1.1.1
react, v0.12.9
react-snippets, v0.2.0
remote-edit, v1.8.21
ruby-block, v0.3.5
set-syntax, v0.3.0
seti-ui, v0.7.1

# Dev
No dev packages
```

**Comment by deanraspa** [comment]
I am pretty sure that editor.getSelection has been deprecated, and you should be using editor.getLastSelection() instead

**Comment by santosh** [comment]
Even if this issue is fixed. I can't do `print("this")` in python file.

**Comment by santosh** [comment]
[Enter steps to reproduce below:]

1. Open a `.py` file.
2. Write `print("anything")`
3. Select `print("anything")`
4. Press Alt+Shift+R

**Atom Version**: 1.0.19
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [atom-runner](https://github.com/lsegal/atom-runner) package, v2.4.6


### Stack Trace

Uncaught TypeError: editor.getSelection is not a function

```
At /C:/Users/Santosh%20Kumar/.atom/packages/atom-runner/lib/atom-runner.coffee:271

TypeError: editor.getSelection is not a function
    at AtomRunner.execute (C:\Users\Santosh Kumar\.atom\packages\atom-runner\lib\atom-runner.coffee:168:33)
    at AtomRunner.run (C:\Users\Santosh Kumar\.atom\packages\atom-runner\lib\atom-runner.coffee:108:6)
    at atom-workspace.<anonymous> (C:\Users\Santosh Kumar\.atom\packages\atom-runner\lib\atom-runner.coffee:70:62)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Santosh Kumar\AppData\Local\atom\app-1.0.19\resources\app.asar\src\command-registry.js:245:29)
    at C:\Users\Santosh Kumar\AppData\Local\atom\app-1.0.19\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\Santosh Kumar\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:524:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\Santosh Kumar\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:347:22)
    at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\Santosh Kumar\AppData\Local\atom\app-1.0.19\resources\app.asar\src\window-event-handler.js:184:20)
```

### Commands

```
     -5:54.4.0 run:file (atom-text-editor.editor.is-focused.vim-mode.insert-mode)
     -5:40 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
  5x -4:39.5.0 run:file (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  2x -1:35.7.0 editor:newline (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -1:30.5.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -1:30.3.0 editor:select-to-first-character-of-line (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  2x -1:25.1.0 run:selection (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:17.2.0 vim-mode:activate-normal-mode (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  4x -0:15 vim-mode:delete (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:07.1.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:04.6.0 vim-mode:activate-linewise-visual-mode (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:02.7.0 run:selection (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "background-tips",
      "bookmarks",
      "deprecation-cop",
      "encoding-selector",
      "exception-reporting",
      "grammar-selector",
      "image-view",
      "package-generator",
      "release-notes",
      "timecop",
      "update-package-dependencies",
      "welcome"
    ],
    "openEmptyEditorOnStart": false,
    "autoHideMenuBar": true
  }
}
```

### Installed Packages

```coffee
# User
atom-runner, v2.4.6
highlight-line, v0.11.0
vim-mode, v0.61.0

# Dev
No dev packages
```

**Comment by lsegal** [comment]
This was merged but there's not been a release yet.

**Comment by santosh** [comment]
When should I expect the release?

**Comment by lsegal** [comment]
I just pushed 2.4.7 now, which should have the fix.

**Comment by santosh** [comment]
Thanks for the update! :smiley:
