### ISSUE TITLE
Failed to activate the atom-runner package

### ISSUE THREAD

**Issue by martonw** [lsegal/atom-runner#92]
[Enter steps to reproduce below:]

1. Install the atom-runner package
2. During the installation and any further time I try to run something I got the below error.

**Atom Version**: 1.0.19
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [atom-runner](https://github.com/lsegal/atom-runner) package, v2.4.6

### Stack Trace

Failed to activate the atom-runner package

```
At Cannot find module 'ansi-to-html'

Error: Cannot find module 'ansi-to-html'
  at Module._resolveFilename (module.js:334:15)
  at Function.Module._resolveFilename (C:\Users\Márton\AppData\Local\atom\app-1.0.19\resources\app.asar\src\module-cache.js:383:52)
  at Function.Module._load (module.js:284:25)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (C:\Users\Márton\.atom\packages\atom-runner\lib\atom-runner-view.coffee:2:14)
  at Object.<anonymous> (C:\Users\Márton\.atom\packages\atom-runner\lib\atom-runner-view.coffee:1:1)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .coffee] (C:\Users\Márton\AppData\Local\atom\app-1.0.19\resources\app.asar\src\compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (C:\Users\Márton\.atom\packages\atom-runner\lib\atom-runner.coffee:8:18)
  at Object.<anonymous> (C:\Users\Márton\.atom\packages\atom-runner\lib\atom-runner.coffee:1:1)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .coffee] (C:\Users\Márton\AppData\Local\atom\app-1.0.19\resources\app.asar\src\compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Package.module.exports.Package.requireMainModule (C:\Users\Márton\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package.js:761:34)
  at Package.module.exports.Package.activateConfig (C:\Users\Márton\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package.js:263:14)
  at Package.module.exports.Package.activateNow (C:\Users\Márton\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package.js:241:14)
  at C:\Users\Márton\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package.js:838:25
  at Emitter.module.exports.Emitter.emit (C:\Users\Márton\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Márton\AppData\Local\atom\app-1.0.19\resources\app.asar\src\command-registry.js:226:20)
  at C:\Users\Márton\AppData\Local\atom\app-1.0.19\resources\app.asar\src\command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (C:\Users\Márton\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\command-palette\lib\command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (C:\Users\Márton\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (C:\Users\Márton\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Márton\AppData\Local\atom\app-1.0.19\resources\app.asar\src\command-registry.js:245:29)
  at C:\Users\Márton\AppData\Local\atom\app-1.0.19\resources\app.asar\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\Márton\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\Márton\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\Márton\AppData\Local\atom\app-1.0.19\resources\app.asar\src\window-event-handler.js:184:20)

```

### Commands

```
     -0:12.8.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  2x -0:07.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:04.9.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:04.5.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -0:03.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:03.6.0 run:selection (atom-text-editor.editor)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-runner, v2.4.6
javascript-snippets, v1.0.0

# Dev
No dev packages
```

**Comment by gmish27** [comment]
Hi, is this issue resolved?

**Comment by martonw** [comment]
Hi - the issue still persists. My atom version is 1.1.0, my atom-runner version is 2.5.2 (updated to latest before testing).

**Comment by lsegal** [comment]
Sorry but I was unable to reproduce this issue. I am testing on Windows 10 with v2.5.2 and was able to cleanly remove the package and re-install from Atom's packages listing. 

This might be a temporal issue, since the [ansi-to-html package](https://www.npmjs.com/package/ansi-to-html) definitely exists. An error that suggests it does not is possibly a networking error, among other things. I would suggest re-trying the install, or if you're tech savvy, going into your `~/.atom/packages/atom-runner` directory and typing `apm install`, which should bring down the correct dependencies.

**Comment by martonw** [comment]
Hi @lsegal - thanks for the note. I ran `apm install` as you suggested and after restarting atom it all works well. So it seems it was indeed some kind of temporal issue.
